export const SEARCHFIELD = 'SEARCHFIELD';
export const PRODUCTITEM = 'PRODUCTITEM';
export const INCREASECART = 'INCREASECART';
export const DECREASECART = 'DECREASECART';
export const REMOVEITEM = 'REMOVEITEM';