export const PRODUCTS = [
    {
        id: 1,
        name: 'iPhone',
        model: '12',
        memory: '64',
        price: '220,000',
        image: '../../images/product/iphone12.jpg',
        color: 'Blue',
        product: 'mobile',
        brand: 'Apple',
        category: 'Flash Sales',
    },
    {
        id: 2,
        name: 'iPhone',
        model: '12',
        memory: '128',
        price: '296,000',
        image: '../../images/product/iphone12-2.jpg',
        color: 'Black',
        product: 'mobile',
        brand: 'Apple',
        category: 'Flash Sales',
    },
    {
        id: 3,
        name: 'iPhone',
        model: '13 Pro',
        memory: '128',
        price: '640,000',
        image: '../../images/product/iphone13pro.jpg',
        color: 'Alpine Green',
        product: 'mobile',
        brand: 'Apple',
        category: 'Top Selling',
    },
    {
        id: 4,
        name: 'iPhone',
        model: '13 Pro Max',
        memory: '256',
        price: '720,000',
        image: '../../images/product/iphone13promax.jpg',
        color: 'Graphite',
        product: 'mobile',
        brand: 'Apple',
        category: 'Blockbuster',
    },
    {
        id: 5,
        name: 'iPhone',
        model: '14',
        memory: '256',
        price: '925,000',
        image: '../../images/product/iphone14.jpg',
        color: 'Red',
        product: 'mobile',
        brand: 'Apple',
        category: 'Blockbuster',
    },
    {
        id: 6,
        name: 'Samsung',
        model: 'M13',
        memory: '64',
        price: '720,000',
        image: '../../images/product/samsungm13.jpg',
        color: 'Midnight Blue',
        product: 'mobile',
        brand: 'Samsung',
        category: 'Blockbuster',

    },
    {

        id: 7,
        name: 'Samsung',
        model: 'S22',
        memory: '256',
        price: '720,000',
        image: '../../images/product/samsungs22.jpg',
        color: 'White',
        product: 'mobile',
        brand: 'Samsung',
        category: '',
    },
    {

        id: 8,
        name: 'XIAOMI Redmi',
        model: 'Note 11',
        memory: '128',
        price: '146,000',
        image: '../../images/product/xiominote11.jpg',
        color: 'Graphite Gray',
        product: 'mobile',
        brand: 'redmi',
        category: 'Blockbuster',
    },
    {

        id: 9,
        name: 'XIAOMI Redmi',
        model: 'A1',
        memory: '32',
        price: '720,000',
        image: '../../images/product/xiomia1.jpg',
        color: 'Black',
        product: 'mobile',
        brand: 'redmi',
        category: '',
    },
    {

        id: 10,
        name: 'OnePlus',
        model: 'Nord CE 2 Lite 5G',
        memory: '128',
        price: '180,000',
        image: '../../images/product/oneplusce.jpg',
        color: 'Blue Tide',
        product: 'mobile',
        brand: 'OnePlus',
        category: 'Blockbuster',
    },
    {

        id: 11,
        name: 'Fire-Boltt',
        model: 'Ninja 2',
        description: 'Full Touch Smartwatch with 30 Workout Modes, Heart Rate Tracking, and 100+ Cloud Watch Faces, 7 Days of extensive Battery',
        price: '34,000',
        image: '../../images/product/ninja2.jpg',
        color: 'black',
        product: 'Electronics',
        brand: 'Fire-Boltt',
        category: 'Blockbuster',
    },
    {

        id: 12,
        name: 'Apple',
        model: 'Watch SE',
        description: '(GPS + Cellular, 44mm)',
        price: '420,000',
        image: '../../images/product/iwatchse.jpg',
        color: 'Space Grey Aluminium Case with Midnight Sport Band',
        product: 'Electronics',
        brand: 'Apple',
        category: 'Flash Sales',
    },
    {

        id: 13,
        name: 'boAt',
        model: 'Rockerz 225 Pro+',
        description: 'Bluetooth Neckband with Upto 40 Hours Playback, ASAP™ Charge, IPX7, Dual Pairing, BT v5.0 and Mic',
        memory: '256',
        price: '16,000',
        image: '../../images/product/boAt225pro.jpg',
        color: 'Teal Green',
        product: 'Electronics',
        brand: 'boAt',
        category: '',
    },
    {

        id: 14,
        name: 'boAt',
        model: 'Type C A325',
        description: 'angle-free, Sturdy Type C Cable with 3A Rapid Charging & 480mbps Data Transmission',
        price: '7000',
        image: '../../images/product/boAt325.jpg',
        color: 'Black',
        product: 'Electronics',
        brand: 'boAt',
        category: 'Flash Sales',
    },
    {

        id: 15,
        name: 'SanDisk',
        model: 'Ultra microSD UHS_I',
        description: 'Card 64GB, 120MB/s R',
        memory: '64',
        price: '14,999',
        image: '../../images/product/sandisk.jpg',
        color: 'White',
        product: 'Electronics',
        brand: 'SanDisk',
        category: '',
    },
    {

        id: 16,
        name: 'HP',
        model: 'X1000',
        description: 'Wired USB Mouse with 3 Handy Buttons, Fast-Moving Scroll Wheel and Optical Sensor works on most Surfaces',
        price: '4,899',
        image: '../../images/product/hpmouse.jpg',
        color: 'Black',
        product: 'Electronics',
        brand: 'HP',
        category: 'Blockbuster',
    },
    {

        id: 17,
        name: 'SanDisk',
        model: 'Cruzer Blade',
        memory: '32',
        price: '24,999',
        image: '../../images/product/flashdrive.jpg',
        color: 'Red-Black',
        product: 'Electronics',
        brand: 'sandisk',
        category: 'Flash Sales',
    },
    {

        id: 18,
        name: 'boAt',
        model: 'Airdopes 121v2',
        description: 'True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls',
        price: '27,999',
        image: '../../images/product/boAtbuds.jpg',
        color: 'Active Black',
        product: 'Electronics',
        brand: 'boAt',
        category: '',
    },
    {

        id: 19,
        name: 'Longitech',
        model: 'B170 Wireless Mouse',
        description: '2.4 GHz with USB Nano Receiver, Optical Tracking, 12-Months Battery Life, Ambidextrous, PC/Mac/Laptop',
        price: '9,799',
        image: '../../images/product/longitech170.jpg',
        color: 'Black',
        product: 'Electronics',
        brand: 'Longitech',
        category: 'Flash Sales',
    },
    {

        id: 20,
        name: 'Dell',
        model: 'KB216',
        description: 'Wired Multimedia USB Keyboard with Super Quite Plunger Keys with Spill-Resistant',
        price: '14,399',
        image: '../../images/product/keyboad.jpg',
        color: 'black',
        product: 'Electronics',
        brand: 'Dell',
        category: '',
    },
    {

        id: 21,
        name: 'American Tourister',
        description: 'Jamaica 80CM Wine RED Soft Suitcase',
        price: '47,899',
        image: '../../images/product/redsuitcase.jpg',
        color: 'Red',
        product: 'fashion',
        category: 'Flash Sales',
    },
    {

        id: 22,
        name: 'Crocs',
        description: 'Unisex Adult Bayaband',
        price: '27,299',
        image: '../../images/product/crocs.jpg',
        color: 'Navy/Pepper',
        product: 'fashion',
        category: 'Flash Sales',
    },
    {

        id: 23,
        name: 'Nivea',
        description: 'Lotion for Dry Skin, Shea Smooth, with Shea Butter, For Men & Women, 400 ml',
        price: '6,499',
        image: '../../images/product/nivea.jpg',
        Scent: 'Shea Butter',
        product: 'fashion',
        brand: 'Nivea',
        category: 'Bluckbuster',
    },
    {

        id: 24,
        name: 'Adidas',
        description: 'Sparx Mens Sd0323g Sneakers',
        price: '32,599',
        image: '../../images/product/adidas.jpg',
        color: 'White Black',
        product: 'fashion',
        brand: 'Adidas',
        category: '',
    },
    {

        id: 25,
        name: 'Fossil Analog',
        description: 'Rose Gold Dial Women\'s Watch-BQ181',
        price: '325,499',
        image: '../../images/product/watch.jpg',
        color: 'Gold',
        product: 'fashion',
        brand: 'Watch',
        category: 'Blockbuster',
    },
    {

        id: 26,
        name: 'Fastrack',
        description: 'Men Square Sunglases',
        price: '42,999',
        image: '../../images/product/sunglasses.jpg',
        color: 'Black',
        product: 'fashion',
        brand: 'Sunglasses',
        category: 'Blockbuster',
    },
    {

        id: 27,
        name: 'Fogg Marco Perfume',
        description: 'Body Spray For Men (Black), Long Lasting, No Gas, Everyday Deodorant and Spray, 150ml',
        price: '4,299',
        image: '../../images/product/fogg.jpg',
        product: 'fashion',
        brand: 'Fogg Marco',
        category: '',
    },
    {

        id: 28,
        name: 'Nivea',
        description: 'Deodorant Roll On, Pearl & Beauty For Women 50ml',
        price: '799',
        image: '../../images/product/rollon.jpg',
        product: 'fashion',
        brand: 'Nivea',
        category: 'Flash Sales',
    },
    {
        id: 29,
        name: 'Jaguar',
        description: 'Classic Black Eau De Toilette, 100 ml',
        price: '73,999',
        image: '../../images/product/fragrance.jpeg',
        product: 'fashion',
        brand: 'Jaguar',
        category: 'Blockbuster',
    },
    {
        id: 30,
        name: 'Hide & Skin',
        description: 'Unisex Leather RFID Blocking Card Holder Cum Minimalistic Wallet (Velvet Brown)',
        price: '27,899',
        image: '../../images/product/wallet.jpeg',
        product: 'fashion',
        brand: 'Wallet',
        category: '',
    },
]